# Generated by Django 2.2.1 on 2019-05-16 02:26

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Evaluadores', '0001_initial'),
        ('Cursos', '0001_initial'),
        ('Rubricas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo_min', models.IntegerField(default=5)),
                ('tiempo_max', models.IntegerField(default=8)),
                ('fecha_inicio', models.DateTimeField(verbose_name=datetime.datetime(2019, 5, 16, 2, 26, 46, 509883, tzinfo=utc))),
                ('fecha_fin', models.DateTimeField(verbose_name=datetime.datetime(2019, 5, 16, 2, 26, 46, 509883, tzinfo=utc))),
                ('estado', models.BooleanField(default=False)),
                ('nombre', models.CharField(max_length=100)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cursos.Course')),
                ('rubrica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rubricas.Rubrica')),
            ],
        ),
        migrations.CreateModel(
            name='FichaEvaluacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_grupo', models.CharField(max_length=15)),
                ('estado_evaluacion', models.CharField(max_length=15)),
                ('tiempo', models.IntegerField(default=0)),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Evaluaciones.Evaluacion')),
                ('evaluador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Evaluadores.Evaluador')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cursos.Grupo')),
                ('presentador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cursos.Alumno')),
            ],
        ),
    ]
