# Generated by Django 2.2.1 on 2019-05-23 01:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Evaluaciones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluacion',
            name='rubrica',
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='estado',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='fecha_fin',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='fecha_inicio',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='tiempo_max',
            field=models.PositiveSmallIntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='tiempo_min',
            field=models.PositiveSmallIntegerField(default=5),
        ),
    ]
