# Generated by Django 2.2.1 on 2019-05-20 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Evaluaciones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluacion',
            name='rubrica',
        ),
    ]
