# Generated by Django 2.2.1 on 2019-05-28 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Rubricas', '0001_initial'),
        ('Evaluaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='rubrica',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Rubricas.Rubrica'),
        ),
    ]
