# Generated by Django 2.2.1 on 2019-05-20 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evaluaciones', '0002_remove_evaluacion_rubrica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacion',
            name='estado',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='fecha_fin',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='fecha_inicio',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='tiempo_max',
            field=models.PositiveSmallIntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='tiempo_min',
            field=models.PositiveSmallIntegerField(default=5),
        ),
    ]
