# Generated by Django 2.2.1 on 2019-05-27 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Evaluaciones', '0002_auto_20190527_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichaevaluacion',
            name='aspectoRubrica',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Rubricas.AspectoRubrica'),
        ),
    ]
