# Generated by Django 2.2.1 on 2019-05-28 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Evaluaciones', '0002_evaluacion_rubrica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacion',
            name='rubrica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Rubricas.Rubrica'),
        ),
    ]
