# Generated by Django 2.2.1 on 2019-05-23 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Evaluaciones', '0002_auto_20190523_0003'),
        ('Evaluaciones', '0002_auto_20190522_2117'),
    ]

    operations = [
    ]
