# Generated by Django 2.2.1 on 2019-05-17 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evaluadores', '0002_evaluador_creado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluador',
            name='correo',
            field=models.EmailField(max_length=50),
        ),
    ]
