# Generated by Django 2.2.1 on 2019-05-20 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Evaluadores', '0004_evaluadoruser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EvaluadorUser',
        ),
    ]
