# Generated by Django 2.2.1 on 2019-05-21 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Evaluadores', '0005_delete_evaluadoruser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('evaluador_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Evaluadores.Evaluador')),
            ],
            bases=('Evaluadores.evaluador',),
        ),
    ]
