# Generated by Django 2.2.1 on 2019-05-27 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('código', models.CharField(max_length=6)),
                ('sección', models.PositiveSmallIntegerField()),
                ('año', models.PositiveSmallIntegerField()),
                ('semestre', models.CharField(max_length=9)),
            ],
            options={
                'unique_together': {('nombre', 'código', 'sección', 'año', 'semestre')},
            },
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12)),
                ('nombre', models.CharField(max_length=30)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cursos.Curso')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cursos.Grupo')),
            ],
        ),
    ]
