# Generated by Django 2.2.1 on 2019-05-28 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Evaluadores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('código', models.CharField(max_length=6)),
                ('sección', models.PositiveSmallIntegerField()),
                ('año', models.PositiveSmallIntegerField()),
                ('semestre', models.CharField(max_length=9)),
            ],
            options={
                'unique_together': {('nombre', 'código', 'sección', 'año', 'semestre')},
            },
        ),
        migrations.CreateModel(
            name='EvaluadoresCurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cursos.Curso')),
                ('evaluador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Evaluadores.Evaluador')),
            ],
            options={
                'unique_together': {('curso', 'evaluador')},
            },
        ),
    ]
