# Generated by Django 2.2.1 on 2019-05-25 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupo',
            name='curso',
        ),
    ]
