# Generated by Django 2.2.1 on 2019-05-18 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='codigo',
            new_name='código',
        ),
        migrations.RenameField(
            model_name='curso',
            old_name='seccion',
            new_name='sección',
        ),
    ]
