# Generated by Django 2.2.1 on 2019-05-19 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0002_auto_20190518_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='sección',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
