# Generated by Django 2.2.1 on 2019-05-10 05:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190510_0111'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='fecha_inicio',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 10, 5, 17, 52, 968058, tzinfo=utc)),
        ),
    ]
