# Generated by Django 2.2.1 on 2019-05-10 05:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_evaluacion_fecha_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='fecha_fin',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='fecha_inicio',
            field=models.DateTimeField(),
        ),
    ]
