# Generated by Django 2.2.1 on 2019-05-10 21:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190510_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluación',
            name='fecha_fin',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 5, 10, 21, 24, 33, 641227, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='evaluación',
            name='fecha_inicio',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 5, 10, 21, 24, 33, 641180, tzinfo=utc)),
        ),
    ]
