# Generated by Django 2.2.1 on 2019-05-10 21:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20190510_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluación',
            name='fecha_fin',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 5, 10, 21, 49, 4, 396409, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='evaluación',
            name='fecha_inicio',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 5, 10, 21, 49, 4, 396362, tzinfo=utc)),
        ),
    ]
