# Generated by Django 2.2.1 on 2019-05-11 04:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20190510_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluación',
            name='fecha_fin',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 5, 11, 4, 15, 44, 667104, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='evaluación',
            name='fecha_inicio',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 5, 11, 4, 15, 44, 667058, tzinfo=utc)),
        ),
    ]
