# Generated by Django 2.2.1 on 2019-05-17 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190510_1846'),
        ('blog', '0015_auto_20190511_0015'),
    ]

    operations = [
    ]
