# Generated by Django 2.2.1 on 2019-05-28 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('run', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('correo', models.EmailField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoGrupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('integrante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alumnos.Alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('integrante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alumnos.Alumno')),
            ],
        ),
    ]
