# Generated by Django 2.2.1 on 2019-05-28 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rubrica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AspectoRubrica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fila', models.IntegerField(default=0)),
                ('columna', models.IntegerField(default=0)),
                ('puntaje', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('nombreFila', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=50)),
                ('rubrica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rubricas.Rubrica')),
            ],
        ),
    ]
