# Generated by Django 2.2.1 on 2019-05-16 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Rubricas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rubrica',
            name='aspects',
        ),
        migrations.RemoveField(
            model_name='rubrica',
            name='description',
        ),
        migrations.RemoveField(
            model_name='rubrica',
            name='score',
        ),
        migrations.AddField(
            model_name='rubrica',
            name='descripcion',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.CreateModel(
            name='AspectoRubrica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fila', models.IntegerField(default=0)),
                ('columna', models.IntegerField(default=0)),
                ('puntaje', models.DecimalField(decimal_places=1, default=0, max_digits=1)),
                ('nombreFila', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=50)),
                ('rubrica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rubricas.Rubrica')),
            ],
        ),
    ]
