# Generated by Django 2.2.1 on 2019-05-23 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rubricas', '0002_auto_20190516_1854'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rubrica',
            old_name='name',
            new_name='nombre',
        ),
    ]
